### ISSUE TITLE
New Rule: use CREATE OR REPLACE

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#35]
** Language Usage / Stored Objects / General**
always use CREATE OR REPLACE instead of only CREATE

**Comment by PhilippSalvisberg** [comment]
from [SonarSource](https://rules.sonarsource.com/plsql/RSPEC-2456?search=%22CREATE%20OR%20REPLACE%22%20should%20be%20used%20instead%20of%20%22CREATE%22):

**"CREATE OR REPLACE" should be used instead of "CREATE"**

When creating a function, procedure, package, package body, type, type body, trigger or library, it is a good practice replace the existing one to avoid errors.

**Noncompliant Code Example**
```
CREATE FUNCTION my_function RETURN PLS_INTEGER AS -- Noncompliant
BEGIN
  RETURN 42;
END;
/
```

**Compliant Solution**
```
CREATE OR REPLACE FUNCTION my_function RETURN PLS_INTEGER AS -- Compliant, no error even if the function already exists
BEGIN
  RETURN 42;
END;
/
```

**Comment by PhilippSalvisberg** [comment]
I tend to agree. The question is: does someone uses create without replace by purpose? E.g. to ensure the statement fails on second execution? Thoughts?

**Comment by S-Koell** [comment]
I would think that a create without a replace is so niche that this rule would make sense.
Because the persons knows what he is doing if he leaves out the "replace" and therefore can ignore that rule easily.
And if a "replace" is forgotten it can lead to problems.

I vote for this rule.

**Comment by PhilippSalvisberg** [comment]
Thanks, so let's add this rule.
