### ISSUE TITLE
New Rule: use FORMAT_ERROR_STACK always with FORMAT_ERROR_BACKTRACE

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#36]
**Language Usage / Exception Handling**
when using DBMS_UTILITY.FORMAT_ERROR_STACK to display an error always follow up with DBMS_UTILITY.FORMAT_ERROR_BACKTRACE

**Comment by PhilippSalvisberg** [comment]
from [SonarQube](https://rules.sonarsource.com/plsql/RSPEC-1059?search=%22DBMS_UTILITY.FORMAT_ERROR_STACK%22%20and%20%22FORMAT_ERROR_BACKTRACE%22%20should%20be%20used%20together):

**"DBMS_UTILITY.FORMAT_ERROR_STACK" and "FORMAT_ERROR_BACKTRACE" should be used together**

Since Oracle 10g, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE is available to get an exception's stack trace, i.e. files and lines that lead up to the exception. When combined with DBMS_UTILITY.FORMAT_ERROR_STACK, which contains the exception error code and message, developers are able quickly identify defects.

This rule verifies that whenever either is used in an exception handler, the other is used as well.

**Noncompliant Code Example**
```
BEGIN
  RAISE_APPLICATION_ERROR(-20000, 'This is an error example');
EXCEPTION
  WHEN OTHERS THEN  -- Noncompliant; only FORMAT_ERROR_STACK is used
    DBMS_OUTPUT.PUT(DBMS_UTILITY.FORMAT_ERROR_STACK);           -- "ORA-20000: This is an error example"
    DBMS_OUTPUT.PUT_LINE('');
END;
/
```
**Compliant Solution**
```
BEGIN
  RAISE_APPLICATION_ERROR(-20000, 'This is an error example');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT(DBMS_UTILITY.FORMAT_ERROR_STACK);           -- "ORA-20000: This is an error example"
    DBMS_OUTPUT.PUT(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);       -- "ORA-06512: at line 2"
    DBMS_OUTPUT.PUT_LINE('');
END;
/
```

**Comment by PhilippSalvisberg** [comment]
Sound reasonable. However, consider the following exception block:

```
   EXCEPTION
      WHEN OTHERS THEN
         -- handle backtrace error stack
         l_backtrace := dbms_utility.format_error_backtrace;
         -- log incident and stop logging
         ...logging.process_stop(
            i_process_id           => l_process_id,
            i_incident_description => SQLERRM || chr(10) || l_backtrace
         );
         -- raise exception after logging
         RAISE;
```

`SQLERRM` was used Instead of `dbms_utility.format_error_stack` in this case. That's ok from my point of view. The sequence of the calls should not matter. Never. It really depends how the logging system works.

Using `format_error_backtrace` together with `SQLERR`, `SQLERRM` or `format_error_stack` makes sense.
