### ISSUE TITLE
New Rule: no oversized item lists for IN clauses

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#51]
**Language Usage / DML & SQL / General**
Avoid lists for IN clauses with more than 1000 items
(not applicable for IN clauses with a subselect)

from [SonarQube](https://rules.sonarsource.com/plsql/type/Code%20Smell/RSPEC-2472)

**Large item lists should not be used with "IN" clauses**

Oracle supports at most 1000 items in a SQL query's IN clause. When more items are given, the exception ORA-01795 maximum number of expressions in a list is 1000 is raised. Thus, IN clauses are not as scalable as joins.

**Noncompliant Code Example**

```sql
BEGIN
  SELECT *
  INTO result
  FROM my_table
  WHERE col1 IN (1, 2, 3, ..., 1001);
END;
```

**Compliant Solution**

```sql
BEGIN
  SELECT my_table.*
  INTO result
  FROM my_table
  JOIN new_in_table
  WHERE my_table.col1 = new_in_table.value;
END;
```

**Comment by PhilippSalvisberg** [comment]
I do not agree with this rule. It's true that an `IN` list is limited to 1000 literals. But to ban the use of `IN` lists due to this limitation is bad thing. Especially since this will have most probably a bad impact on performance.

IMHO in static code this is never a problem. In dynamic code, however, it may happen that the limit of 1000 entries is reached. But dynamic code is out-of-scope for static code analysis. Nevertheless it could be a guideline. A guideline must not necessarily be "checkable". But the rule as stated here is simply not useful.
