### ISSUE TITLE
New Rule: REF CURSER with return types

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#54]
**Language Usage / Control Structures / CURSOR** or **Language Usage / Variables & Types / General**
Avoid usage of weak REF CURSOR types

from [SonarCube](https://rules.sonarsource.com/plsql/type/Code%20Smell/RSPEC-2570)

**Weak "REF CURSOR" types should not be used**

Weak REF CURSOR types are harder to work with than ones with a return type. Indeed, the compiler's type-checker is unable to make some verifications, which are then delayed till runtime.

When the use of weak REF CURSOR is required, it is best to use the SYS_REFCURSOR built-in type instead of defining a new one.

This rule's sysRefCursorAllowed parameter can be used to control whether or not the usage of SYS_REFCURSOR is allowed.

**Noncompliant Code Example**

```sql
DECLARE
  TYPE dualCursorType IS REF CURSOR;
  dualCursor dualCursorType;

  otherCursor SYS_REFCURSOR;                              -- Compliant or non-compliant, depending on the "sysRefCursorAllowed" parameter
BEGIN
  otherCursor := dualCursor;                              -- Works
END;
```

**Compliant Solution**

```sql
DECLARE
  TYPE dualCursorType IS REF CURSOR RETURN DUAL%ROWTYPE;
  dualCursor dualCursorType;

  TYPE otherCursorType IS REF CURSOR RETURN a%ROWTYPE;
  otherCursor otherCursorType;
BEGIN
  otherCursor := dualCursor;                              -- raises PLS-00382: expression is of wrong type, which makes debugging easier
END;
```

**Comment by PhilippSalvisberg** [comment]
I do not agree with the rule as it is stated here. 

`SYS_REFCURSOR` has been introduced with Oracle Database version 9i. Since then there is no need to define explicitly a weak cursor anymore. Hence every week cursor could be easily replaced with `SYS_REFCURSOR`. So far I agree.

But forbidding the use of `SYS_REFCURSOR` in general goes too far for me. 

I agree to the rule if the scope is reduced to explicit weak cursor declarations, where we suggest using `SYS_REFCURSOR` instead. We can even elaborate the advantages of strong cursor types, but we should refrain from forbidding weak cursors.

Thoughts?

**Comment by rogertroller** [comment]
Agree with your disagreement ... i toppled this rule from our ruleset.

**Comment by PhilippSalvisberg** [comment]
Thanks @rogertroller. How about reducing the scope to change "legacy weak cursors" to `SYS_REFCURSOR`s?
