### ISSUE TITLE
Missing prefix for check constraint

### ISSUE THREAD

**Issue by lasjen** [Trivadis/plsql-and-sql-coding-guidelines#55]
The current naming rules for "Database Object Naming Conventions" are missing prefix for "Check constraint". I prefer to name all constraints. Check constraints I name with prefix "_ck", and the special case "NOT NULL" I prefix "_nn".

**Comment by PhilippSalvisberg** [comment]
Thanks @lasjen for reporting this. Yes, that's correct. Naming for primary key, unique key and foreign key constraints are defined, but check constraints are missing.

**Comment by PhilippSalvisberg** [comment]
@rogertroller, what would be your recommendation?

**Comment by rogertroller** [comment]
My first thoughts when I read the title were .... rather be a suffix than a prefix just because I love to have the things together, that belong to the same object and not those of same type (ordering issue) but @lasjen is talking about suffixes and therefore _ck looks good to me given the fact that we have _pk and _uk for primary key and unique key constraints.
