### ISSUE TITLE
G-3120 (and others) Minor update - use USING clause

### ISSUE THREAD

**Issue by RichardSoule** [Trivadis/plsql-and-sql-coding-guidelines#60]
The 'better' and 'good' queries should use the USING clause instead of the ON clause. It's less code, easier to understand and less prone to mistakes. True it sometimes confuses the old 'Oracle proprietary' folks because you can't use a table alias in front of the joined column, but once you get used to not doing that it works just fine.

instead of:

from      employee   e
       join department d on (e.department_id = d.department_id)

use:

from      employee   e
       join department d using (department_id)

**Comment by RichardSoule** [comment]
Same thing for G-3130: Try to use ANSI SQL-92 join syntax.

**Comment by RichardSoule** [comment]
Same thing for G-3190.

**Comment by PhilippSalvisberg** [comment]
The `USING` clause addresses a main flaw of a `NATURAL` join. I like the fact that it formally describes/identifies an equi-join. However, there are some minor things I do not like.

- The `USING` clause is applicable only for a subset of equi-joins.

  In cases where the PK/FK columns are named differently, you still have to use an `ON` condition. Even with strict naming conventions this cannot be completely avoided (e.g. for recursive structures or role specific relationships which are not normalized). Advertising the `USING` clause leads to more complicated standards (in case of ... otherwise ...). This does not really simplify things. The `ON` condition on the other hand works for all cases of an equi-join.

- The `USING` clause has an impact on the projection/available columns.

   A column listed in the `USING` clause is reduced to one. There is no way to access the value of the outer joined column, e.g. in the `WHERE` clause to filter out some outer joined rows based on the join column. You have to use some other `NOT NULL` column, if available or rewrite the query using `(NOT) EXISTS` or `(NOT) IN`. Even for `INNER` joins this makes things more complicated. For example the rule [G-3120](https://trivadis.github.io/plsql-and-sql-coding-guidelines/v3.3/4-language-usage/3-dml-and-sql/1-general/g-3120/) is not applicable for join columns. Again we have to adapt the standard to cover such exceptions. This leads to standards which are more difficult to understand and to apply.

I discussed this with some of my colleagues (@kibeha, @rogertroller and others) and they agreed that it is not worth to make the standard more difficult to apply in favor of the USING clause.
