### ISSUE TITLE
Change naming conventions for tables wrapped by editioning views

### ISSUE THREAD

**Issue by RichardSoule** [Trivadis/plsql-and-sql-coding-guidelines#75]
I noticed that you decided to include some brief notes on EBR and went with what appears to be a suggestion to use 'take the employees table, rename it to employees_eb' and then 'cover it with an Editioning View named employees'.

After watching Bryn's day-long training on EBR multiple times (https://www.youtube.com/playlist?list=PL22OaGrT53hVXrAYvG2CYnZ0eKvDxIcg8), taking extensive notes, and developing hands-on experience with EBR and putting the accumulated knowledge into a 'Demysting Edition Based Redefinition' presentation (about 1.5 hours or so), I'm going to suggest that this suggestion is going to 'miss the mark'.

Editioning Views on base tables are whole brand new object types. EBR is really the only high availability solution that is implemented purely by developers doing something totally different than they did before (DataGuard, for instance, is all done by DBAs). With EBR in place, developers only write code against Editioning Views, and not against base tables (with the possible exception of auditing triggers). 

When developers build against a database with Editioning Views it should be totally apparent to those developers that "no regular code should ever be written against the base table". Bryn recommends using lowercase for the table name and appending an underscore on the name, but that recommendation was developed in the days of 30 character object names and, I believe, without taking into account EBR migration over time, but instead just doing a 'big bang' approach.

If a team is _really_ using EBR across the board, then all base tables will be covered by the 'old table names'. However, it is not unusual to tackle EBR in stages and have, at least for a while, a mixture of some regular tables and some 'base tables covered by editioning views'. 

Using lower case base table names that are prepended with an underscore does a few things that greatly assist development teams through the transition and after EBR is implemented across the board. First, there is no 'temptation to make the mistake of using a base table' because the only way to use a base table is to enclose it in double-quotes (which is annoying as all get out). Second, by prepending an underscore to the table name, all base tables that are currently covered by an editioning view will appear at the beginning of the list of tables (almost every tool uses alphabetical order and underscores come before actual letters). I usually even create a dummy table named ``"__EBR in play, go look in Views__"`` once all base tables are covered, and even sometimes before every base table is covered.

A 'generic' suffix of ``_EB`` provides none of those benefits. Even ``_EBR`` would be better. Or maybe even something like (for the employees table for example) ``EMPLOYEES_BASE_TABLE_COVERED_BY_EMPLOYEES_EDITIONING_VIEW``. A developer that wasn't yet familiar with EBR could easily make the mistake of using ``EMPLOYEES_EB`` because 'it has all the right columns'. But they would be much more likely to ask questions if the ``EMPLOYEES`` base table was named ``"_employees"`` or ``EMPLOYEES_BASE_TABLE_COVERED_BY_EMPLOYEES_EDITIONING_VIEW``.

These are just some thoughts from actual EBR use...

**Comment by PhilippSalvisberg** [comment]
My understanding is, that this issue is addressing the following sentence in the [table section of the naming Conventions chapter](https://trivadis.github.io/plsql-and-sql-coding-guidelines/v3.5/2-naming-conventions/naming-conventions/#table):

> Suffixed by `_eb` when protected by an editioning view.

It’s suggested to name a table protected (wrapped/covered) by an editioning view differently. The following alternatives are considered better (ordered by preference):

* Name of the editioning view as quoted identifier in lowercase, prefixed by an underscore, e.g `_employees`
* Name of the editioning view suffixed by `_base_table_covered_by_{name_of_the_editioning_view}_editioning_view`, e.g. `_employess_base_table_covered_by_employees_editioning_view`
* Name of the editioning view suffixed by `_ebr`, e.g. `employees_ebr`

The first variant uses quoted names. This violates our naming conventions for PL/SQL. Hence it is disregarded.

The second variant is quite verbose. You still have to write and maintain some code using this table. Such a suffix will make the code more difficult to read. Furthermore it is applicable for Oracle Database version 12.2 and higher only. Hence, this variant is also disregarded. 

The third variant just adds an `r` to the suffix (`_ebr` instead of `_eb`). That’s viable option. However, the suffix `_eb` is chosen as abbreviation for “editioning base”. Tables classified with such a suffix are wrapped by an editioning view. Application code must use editioning view instead of the underlying table (whenever technically feasible). “EBR” is the abbreviation for edition-based redefinition, naming the whole feature set. So the term “EBR” is really too broad. Hence, this variant is also disregarded.

I understand that using a ridiculous or awkward  name for a table wrapped by an editioning view would reduce the risk of such a table being used in the wrong context. However, I do not agree with such a problem solving strategy. I don't want to set a precedent for impractical naming conventions for objects that are intentionally rarely used. There are better ways to ensure objects are used only in the intended ways. In this case, this can easily be achieved by querying some Oracle data dictionary views or by implementing a PL/SQL Cop check. Another way is to store tables and their editioning view in a dedicated schema. Grant only the editioning views to the application schemas. Of course you still have to check, that the base tables are still not granted. Whatever you do, if you really care about code quality these checks should become part of your CI/CD environment.
