### ISSUE TITLE
G-5040: "When others" should be allowed for Logger with RAISE

### ISSUE THREAD

**Issue by S-Koell** [Trivadis/plsql-and-sql-coding-guidelines#77]
The OraLogger best practice ([Link](https://github.com/OraOpenSource/Logger/blob/master/docs/Best%20Practices.md)) looks like this:

```
exception
    when others then
      logger.log_error('Unhandled Exception', l_scope, null, l_params);
      raise;
  end todo_proc_name;
```

This will always give me 
> G-5040: Avoid use of WHEN OTHERS clause in an exception section without any other specific handlers.

I also dont want to disable this rule, because  in general it's good. But with logging the error and reraising it I dont see any problem with it. 
Could there be an exception for this check when doing a raise (and logging maybe) inside the "WHEN OTHERS"?
(it really bothers me because we use this practice for all fkt/procs and therefore get a ton of these PLSQL Cop warnings)

**Comment by PhilippSalvisberg** [comment]
Hi @S-Koell,

Thank you very much for your first contribution. I agree with your reasoning. Logger also stores the error stack, so the source of the error is available in the log table. 

I think it's worth to change this rule to cover this exception. I do not want to make a Logger specific exception, since not everyone is using Logger. So, I think about documenting the intention and requiring that `raise` is the last statement of the `when others` exception handler, if this is the only exception handler. 

This repo covers the guidelines only. However, the PL/SQL Cop validator will be amended accordingly soon after releasing a new guideline version.

**Comment by S-Koell** [comment]
> This repo covers the guidelines only.

I know but I didnt know where the best place for the PLSQL Cop suggestions would be so I thought here might be okay :)

> I do not want to make a Logger specific exception, since not everyone is using Logger. So, I think about documenting the intention and requiring that raise is the last statement of the when others exception handler, if this is the only exception handler.

That was also my way of reasoning. Glad we agree.

**Comment by PhilippSalvisberg** [comment]
>> This repo covers the guidelines only.

>I know but I didnt know where the best place for the PLSQL Cop suggestions would be so I thought here might be okay :)

It's perfectly OK, since in this case a clarification of the rule is necessary. 

Right now you can ask questions regarding the PL/SQL Cop validator in [this forum](https://www.salvis.com/blog/forum/plsql-cop/). We accept also issues regarding the provided PL/SQL Cop validator in [this GitHub repo](https://github.com/Trivadis/cop-validators).
