### ISSUE TITLE
G-1050: Exception for Logger calls

### ISSUE THREAD

**Issue by S-Koell** [Trivadis/plsql-and-sql-coding-guidelines#78]
When using the OraLogger ([Link](https://github.com/OraOpenSource/Logger/blob/master/docs/Best%20Practices.md)) the following code to append parameters is used often:

```logger.append_param(p_params =>l_params, p_name => 'p_param1_todo', p_val => p_param1_todo);```

This will always give me 
> G-1050: Avoid using literals in your code.

for p_name. Which is of course correct. But the alternative would be to have a constant for every parameter and variable of interest and in every proc/fkt which is in my opinion huge overkill as demonstrated here:

```
procedure todo_proc_name(p_param1_todo in varchar2)
  as
    l_my_important_var number := 1;
    l_my_important_var_logger constant varchar2(30) := 'l_my_important_var ';
    l_p_param1_todo_logger    constant varchar2(30) := 'p_param1_todo';

    l_scope constant logger_logs.scope%type := gc_scope_prefix || 'todo_proc_name';
    l_params logger.tab_param;

  begin
    logger.append_param(p_params => l_params, p_name =>  l_p_param1_todo_logger  , p_val => p_param1_todo);
    logger.log(constants.log_start, l_scope, null, l_params);
       ...

    l_my_important_var := 2;
    logger.append_param(p_params => l_params, p_name => l_my_important_var_logger , p_val => l_my_important_var );
    logger.log(constants.log_end, l_scope, null, l_params );
  end todo_proc_name;
```

And the Logger Text ( logger.log_error('Hardcoded error text'); ) should also be ignored in my opinion.

**Comment by PhilippSalvisberg** [comment]
G-1050 is one of those guidelines I recommend to disable (after getting an initial expression and defining some TODOs). It was a pain to create examples which do not violate this rule. 

What you are describing is just one exception. There are also good reasons for using literals in SQL statements. The idea of the guideline is to consider using constants instead of literals.

Instead of adding exceptions to this rule, it would make sense to extend the reasoning and also mention some examples where literals are OK.

**Comment by PhilippSalvisberg** [comment]
This is not a "hard" rule. It leads to a lot of false positives when checking this mechanically.

**Comment by S-Koell** [comment]
> What you are describing is just one exception. There are also good reasons for using literals in SQL statements. The idea of the guideline is to consider using constants instead of literals.

I agree. But these cases are way more rare than the logging. It's okay for me to ignore this error twice or so in a package , eg for SQL. But with the logger it is polluting the result of the check big time.

> G-1050 is one of those guidelines I recommend to disable (after getting an initial impression and defining some TODOs).

I dont think I would agree here. I think it is good to be constantly reminded that a hardcoding is used in every other case. Then the dev can decide if it's still okay. But with logging it should always be ignored.

It's like the 
> G-7460: Try to define your packaged/standalone function deterministic if appropriate

which I will keep because 5-10 of these messages per Package are okay and will remind you of thinking about what your function does and if it is deterministic.
Same for hardcoding. I'd like to be reminded but not for the logger which will be in the high double or triple digit numbers on warnings.

I think that you are hesitating because the logger is not standard and would even maybe need to be a setting (logger package name) to work correctly with the PLSQL Cop.
And I would agree that this is not a "beautful" solution.
But for me disabling isnt a good option and the polluted result is also bad ...

Is there maybe a way to get this handled in a custom validator?

**Comment by PhilippSalvisberg** [comment]
>It's like the
>>G-7460: Try to define your packaged/standalone function deterministic if appropriate
>
>which I will keep because 5-10 of these messages per Package are okay and will remind you of thinking >about what your function does and if it is deterministic.

I do not agree. I don't want to revisit every warning again and again. There are two options

a) disable the check
b) ignore a false positive with a `-- NOSONAR` comment

The second option is only feasible if it is a rare case otherwise I'm polluting my code with `-- NOSONAR` comments. - So I end up disabling all check causing a lot of false positives. 

>I think that you are hesitating because the logger is not standard and would even maybe need to be a setting (logger package name) to work correctly with the PLSQL Cop.

Right. In this case a validator would need additional, configurable input. But that's for sure not in scope of the guidelines.

>Is there maybe a way to get this handled in a custom validator?

Of course. You can extend the standard validator and override the implementation for G-1050.

**Comment by S-Koell** [comment]
> Of course. You can extend the standard validator and override the implementation for G-1050.

If thats the case I will do this. Thanks!

**Comment by PhilippSalvisberg** [comment]
Reopend to change description of rule. 

>Extend the reasoning and also mention some examples where literals are OK.
