### ISSUE TITLE
(Question) Is there any automation of the formatting?

### ISSUE THREAD

**Issue by danijelst** [Trivadis/plsql-and-sql-coding-guidelines#82]
In the chapter [Formatting Rules](https://trivadis.github.io/plsql-and-sql-coding-guidelines/v3.6/3-coding-style/coding-style/#rules) some basic rules are described how to format the code.

Are you doing this all manually or do you have any tools supporting any automation for this?

I have tried to setup SQL Developer Formatter to use those rules, but I failed.

**Comment by PhilippSalvisberg** [comment]
Hi @danijelst,  that is a good question. 

In fact, I'm formatting the code manually when using SQL Developer, but mostly because I typically deal a lot of customer/project specific code where I have to adjust to formatting styles. However, it should be possible to come up with some settings that cover these rules (more or less).

I keep this issue open and will post links to preference settings for common IDEs (for sure PL/SQL Developer and SQL Developer). I'll create most probably in a dedicated GitHub repository for that.

**Comment by PhilippSalvisberg** [comment]
created https://github.com/Trivadis/plsql-formatter-settings with formatter setting for SQL Developer and PL/SQL Developer

**Comment by mhoys** [comment]
Maybe this can help?
https://www.thatjeffsmith.com/archive/2017/03/sqlcl-setting-up-the-formatter/

Matthias
